spring:
  application:
    name: stash

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/stash}
      database: ${MONGODB_DATABASE:stash}

  jackson:
    time-zone: Asia/Seoul

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 9090
  shutdown: graceful

logging:
  level:
    root: INFO
    com.ravit.stash: DEBUG
