spring:
  profiles:
    active: local

  application:
    name: stash

  jackson:
    time-zone: Asia/Seoul

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 9090
  shutdown: graceful

logging:
  level:
    root: INFO
    com.ravit.stash: DEBUG

ai:
  gemini:
    key: ${AI_GEMINI_KEY:}
    model: gemini-2.5-flash
    max-tokens: 8192
    temperature: 0.7

google:
  calendar:
    application-name: stash
    calendar-id: primary
